//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.17929 版自动生成。
// 
#pragma warning disable 1591

namespace SyncInsideDataToOutside.OutsideWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseEntry))]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SMC_UnitSyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback SMC_UserSyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback PackagePictuerSyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback PackageManualSyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback PackageFAQSyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback PackageExtSyncOperationCompleted;
        
        private System.Threading.SendOrPostCallback PackageFilesSyncOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::SyncInsideDataToOutside.Properties.Settings.Default.SyncInsideDataToOutside_OutsideWS_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SMC_UnitSyncCompletedEventHandler SMC_UnitSyncCompleted;
        
        /// <remarks/>
        public event SMC_UserSyncCompletedEventHandler SMC_UserSyncCompleted;
        
        /// <remarks/>
        public event PackagePictuerSyncCompletedEventHandler PackagePictuerSyncCompleted;
        
        /// <remarks/>
        public event PackageManualSyncCompletedEventHandler PackageManualSyncCompleted;
        
        /// <remarks/>
        public event PackageFAQSyncCompletedEventHandler PackageFAQSyncCompleted;
        
        /// <remarks/>
        public event PackageExtSyncCompletedEventHandler PackageExtSyncCompleted;
        
        /// <remarks/>
        public event PackageFilesSyncCompletedEventHandler PackageFilesSyncCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SMC_UnitSync", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SMC_UnitSync(SMC_Unit[] units) {
            object[] results = this.Invoke("SMC_UnitSync", new object[] {
                        units});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SMC_UnitSyncAsync(SMC_Unit[] units) {
            this.SMC_UnitSyncAsync(units, null);
        }
        
        /// <remarks/>
        public void SMC_UnitSyncAsync(SMC_Unit[] units, object userState) {
            if ((this.SMC_UnitSyncOperationCompleted == null)) {
                this.SMC_UnitSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSMC_UnitSyncOperationCompleted);
            }
            this.InvokeAsync("SMC_UnitSync", new object[] {
                        units}, this.SMC_UnitSyncOperationCompleted, userState);
        }
        
        private void OnSMC_UnitSyncOperationCompleted(object arg) {
            if ((this.SMC_UnitSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SMC_UnitSyncCompleted(this, new SMC_UnitSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SMC_UserSync", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SMC_UserSync(SMC_User[] users) {
            object[] results = this.Invoke("SMC_UserSync", new object[] {
                        users});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SMC_UserSyncAsync(SMC_User[] users) {
            this.SMC_UserSyncAsync(users, null);
        }
        
        /// <remarks/>
        public void SMC_UserSyncAsync(SMC_User[] users, object userState) {
            if ((this.SMC_UserSyncOperationCompleted == null)) {
                this.SMC_UserSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSMC_UserSyncOperationCompleted);
            }
            this.InvokeAsync("SMC_UserSync", new object[] {
                        users}, this.SMC_UserSyncOperationCompleted, userState);
        }
        
        private void OnSMC_UserSyncOperationCompleted(object arg) {
            if ((this.SMC_UserSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SMC_UserSyncCompleted(this, new SMC_UserSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PackagePictuerSync", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PackagePictuerSync(SMC_PackagePicture entity) {
            object[] results = this.Invoke("PackagePictuerSync", new object[] {
                        entity});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PackagePictuerSyncAsync(SMC_PackagePicture entity) {
            this.PackagePictuerSyncAsync(entity, null);
        }
        
        /// <remarks/>
        public void PackagePictuerSyncAsync(SMC_PackagePicture entity, object userState) {
            if ((this.PackagePictuerSyncOperationCompleted == null)) {
                this.PackagePictuerSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPackagePictuerSyncOperationCompleted);
            }
            this.InvokeAsync("PackagePictuerSync", new object[] {
                        entity}, this.PackagePictuerSyncOperationCompleted, userState);
        }
        
        private void OnPackagePictuerSyncOperationCompleted(object arg) {
            if ((this.PackagePictuerSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PackagePictuerSyncCompleted(this, new PackagePictuerSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PackageManualSync", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PackageManualSync(SMC_PackageManual entity) {
            object[] results = this.Invoke("PackageManualSync", new object[] {
                        entity});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PackageManualSyncAsync(SMC_PackageManual entity) {
            this.PackageManualSyncAsync(entity, null);
        }
        
        /// <remarks/>
        public void PackageManualSyncAsync(SMC_PackageManual entity, object userState) {
            if ((this.PackageManualSyncOperationCompleted == null)) {
                this.PackageManualSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPackageManualSyncOperationCompleted);
            }
            this.InvokeAsync("PackageManualSync", new object[] {
                        entity}, this.PackageManualSyncOperationCompleted, userState);
        }
        
        private void OnPackageManualSyncOperationCompleted(object arg) {
            if ((this.PackageManualSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PackageManualSyncCompleted(this, new PackageManualSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PackageFAQSync", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PackageFAQSync(SMC_PackageFAQ faq) {
            object[] results = this.Invoke("PackageFAQSync", new object[] {
                        faq});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PackageFAQSyncAsync(SMC_PackageFAQ faq) {
            this.PackageFAQSyncAsync(faq, null);
        }
        
        /// <remarks/>
        public void PackageFAQSyncAsync(SMC_PackageFAQ faq, object userState) {
            if ((this.PackageFAQSyncOperationCompleted == null)) {
                this.PackageFAQSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPackageFAQSyncOperationCompleted);
            }
            this.InvokeAsync("PackageFAQSync", new object[] {
                        faq}, this.PackageFAQSyncOperationCompleted, userState);
        }
        
        private void OnPackageFAQSyncOperationCompleted(object arg) {
            if ((this.PackageFAQSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PackageFAQSyncCompleted(this, new PackageFAQSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PackageExtSync", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PackageExtSync(SMC_PackageExt entity) {
            object[] results = this.Invoke("PackageExtSync", new object[] {
                        entity});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PackageExtSyncAsync(SMC_PackageExt entity) {
            this.PackageExtSyncAsync(entity, null);
        }
        
        /// <remarks/>
        public void PackageExtSyncAsync(SMC_PackageExt entity, object userState) {
            if ((this.PackageExtSyncOperationCompleted == null)) {
                this.PackageExtSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPackageExtSyncOperationCompleted);
            }
            this.InvokeAsync("PackageExtSync", new object[] {
                        entity}, this.PackageExtSyncOperationCompleted, userState);
        }
        
        private void OnPackageExtSyncOperationCompleted(object arg) {
            if ((this.PackageExtSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PackageExtSyncCompleted(this, new PackageExtSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PackageFilesSync", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PackageFilesSync(FileEntity[] files, int pe_id) {
            object[] results = this.Invoke("PackageFilesSync", new object[] {
                        files,
                        pe_id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PackageFilesSyncAsync(FileEntity[] files, int pe_id) {
            this.PackageFilesSyncAsync(files, pe_id, null);
        }
        
        /// <remarks/>
        public void PackageFilesSyncAsync(FileEntity[] files, int pe_id, object userState) {
            if ((this.PackageFilesSyncOperationCompleted == null)) {
                this.PackageFilesSyncOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPackageFilesSyncOperationCompleted);
            }
            this.InvokeAsync("PackageFilesSync", new object[] {
                        files,
                        pe_id}, this.PackageFilesSyncOperationCompleted, userState);
        }
        
        private void OnPackageFilesSyncOperationCompleted(object arg) {
            if ((this.PackageFilesSyncCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PackageFilesSyncCompleted(this, new PackageFilesSyncCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SMC_Unit : BaseEntry {
        
        private int unit_IDField;
        
        private string unit_NameField;
        
        private int upper_Unit_IDField;
        
        private string unit_DemoField;
        
        private string unit_PathField;
        
        private System.DateTime unit_CreatedTimeField;
        
        private string unit_CreatedUserField;
        
        private System.DateTime unit_UpdateTimeField;
        
        private string unit_UpdateUserField;
        
        private int unit_SequenceField;
        
        /// <remarks/>
        public int Unit_ID {
            get {
                return this.unit_IDField;
            }
            set {
                this.unit_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Unit_Name {
            get {
                return this.unit_NameField;
            }
            set {
                this.unit_NameField = value;
            }
        }
        
        /// <remarks/>
        public int Upper_Unit_ID {
            get {
                return this.upper_Unit_IDField;
            }
            set {
                this.upper_Unit_IDField = value;
            }
        }
        
        /// <remarks/>
        public string Unit_Demo {
            get {
                return this.unit_DemoField;
            }
            set {
                this.unit_DemoField = value;
            }
        }
        
        /// <remarks/>
        public string Unit_Path {
            get {
                return this.unit_PathField;
            }
            set {
                this.unit_PathField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Unit_CreatedTime {
            get {
                return this.unit_CreatedTimeField;
            }
            set {
                this.unit_CreatedTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Unit_CreatedUser {
            get {
                return this.unit_CreatedUserField;
            }
            set {
                this.unit_CreatedUserField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Unit_UpdateTime {
            get {
                return this.unit_UpdateTimeField;
            }
            set {
                this.unit_UpdateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Unit_UpdateUser {
            get {
                return this.unit_UpdateUserField;
            }
            set {
                this.unit_UpdateUserField = value;
            }
        }
        
        /// <remarks/>
        public int Unit_Sequence {
            get {
                return this.unit_SequenceField;
            }
            set {
                this.unit_SequenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMC_PackageExt))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMC_PackageFAQ))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMC_PackageManual))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMC_PackagePicture))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMC_User))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SMC_Unit))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class BaseEntry {
        
        private EnumObjectState objectEntryStateField;
        
        /// <remarks/>
        public EnumObjectState ObjectEntryState {
            get {
                return this.objectEntryStateField;
            }
            set {
                this.objectEntryStateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EnumObjectState {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Added,
        
        /// <remarks/>
        Upded,
        
        /// <remarks/>
        Deleted,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileEntity {
        
        private string fileNameField;
        
        private byte[] contentField;
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SMC_PackageExt : BaseEntry {
        
        private int pe_idField;
        
        private System.DateTime pe_UpdateTimeField;
        
        private string pe_UpdateUidField;
        
        private string pe_CreateUidField;
        
        private string pe_DownloadUriField;
        
        private string pe_BuildVerField;
        
        private string pe_VersionField;
        
        private string pe_DescriptionField;
        
        private string pe_DisplayNameField;
        
        private string pe_ClientTypeField;
        
        private string pe_IsTJField;
        
        private string pe_IsBBField;
        
        private string pe_PictureUrlField;
        
        private string pe_2dPictureUrlField;
        
        private string pe_FirmwareField;
        
        private string tableNameField;
        
        private string pe_UnitCodeField;
        
        private string pe_UnitNameField;
        
        private string pe_NameField;
        
        private int tableIDField;
        
        private int pe_DownCountField;
        
        private int pe_SizeField;
        
        private System.DateTime pe_CreatedTimeField;
        
        private string pe_CategoryField;
        
        private string pe_CategoryIDField;
        
        /// <remarks/>
        public int pe_id {
            get {
                return this.pe_idField;
            }
            set {
                this.pe_idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime pe_UpdateTime {
            get {
                return this.pe_UpdateTimeField;
            }
            set {
                this.pe_UpdateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string pe_UpdateUid {
            get {
                return this.pe_UpdateUidField;
            }
            set {
                this.pe_UpdateUidField = value;
            }
        }
        
        /// <remarks/>
        public string pe_CreateUid {
            get {
                return this.pe_CreateUidField;
            }
            set {
                this.pe_CreateUidField = value;
            }
        }
        
        /// <remarks/>
        public string pe_DownloadUri {
            get {
                return this.pe_DownloadUriField;
            }
            set {
                this.pe_DownloadUriField = value;
            }
        }
        
        /// <remarks/>
        public string pe_BuildVer {
            get {
                return this.pe_BuildVerField;
            }
            set {
                this.pe_BuildVerField = value;
            }
        }
        
        /// <remarks/>
        public string pe_Version {
            get {
                return this.pe_VersionField;
            }
            set {
                this.pe_VersionField = value;
            }
        }
        
        /// <remarks/>
        public string pe_Description {
            get {
                return this.pe_DescriptionField;
            }
            set {
                this.pe_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string pe_DisplayName {
            get {
                return this.pe_DisplayNameField;
            }
            set {
                this.pe_DisplayNameField = value;
            }
        }
        
        /// <remarks/>
        public string pe_ClientType {
            get {
                return this.pe_ClientTypeField;
            }
            set {
                this.pe_ClientTypeField = value;
            }
        }
        
        /// <remarks/>
        public string pe_IsTJ {
            get {
                return this.pe_IsTJField;
            }
            set {
                this.pe_IsTJField = value;
            }
        }
        
        /// <remarks/>
        public string pe_IsBB {
            get {
                return this.pe_IsBBField;
            }
            set {
                this.pe_IsBBField = value;
            }
        }
        
        /// <remarks/>
        public string pe_PictureUrl {
            get {
                return this.pe_PictureUrlField;
            }
            set {
                this.pe_PictureUrlField = value;
            }
        }
        
        /// <remarks/>
        public string pe_2dPictureUrl {
            get {
                return this.pe_2dPictureUrlField;
            }
            set {
                this.pe_2dPictureUrlField = value;
            }
        }
        
        /// <remarks/>
        public string pe_Firmware {
            get {
                return this.pe_FirmwareField;
            }
            set {
                this.pe_FirmwareField = value;
            }
        }
        
        /// <remarks/>
        public string TableName {
            get {
                return this.tableNameField;
            }
            set {
                this.tableNameField = value;
            }
        }
        
        /// <remarks/>
        public string pe_UnitCode {
            get {
                return this.pe_UnitCodeField;
            }
            set {
                this.pe_UnitCodeField = value;
            }
        }
        
        /// <remarks/>
        public string pe_UnitName {
            get {
                return this.pe_UnitNameField;
            }
            set {
                this.pe_UnitNameField = value;
            }
        }
        
        /// <remarks/>
        public string pe_Name {
            get {
                return this.pe_NameField;
            }
            set {
                this.pe_NameField = value;
            }
        }
        
        /// <remarks/>
        public int TableID {
            get {
                return this.tableIDField;
            }
            set {
                this.tableIDField = value;
            }
        }
        
        /// <remarks/>
        public int pe_DownCount {
            get {
                return this.pe_DownCountField;
            }
            set {
                this.pe_DownCountField = value;
            }
        }
        
        /// <remarks/>
        public int pe_Size {
            get {
                return this.pe_SizeField;
            }
            set {
                this.pe_SizeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime pe_CreatedTime {
            get {
                return this.pe_CreatedTimeField;
            }
            set {
                this.pe_CreatedTimeField = value;
            }
        }
        
        /// <remarks/>
        public string pe_Category {
            get {
                return this.pe_CategoryField;
            }
            set {
                this.pe_CategoryField = value;
            }
        }
        
        /// <remarks/>
        public string pe_CategoryID {
            get {
                return this.pe_CategoryIDField;
            }
            set {
                this.pe_CategoryIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SMC_PackageFAQ : BaseEntry {
        
        private int pf_idField;
        
        private string pf_uidField;
        
        private string pf_unameField;
        
        private string pf_questionField;
        
        private string pf_answerField;
        
        private System.DateTime pf_askdateField;
        
        private string pf_askemailField;
        
        private int pe_idField;
        
        private string pf_askmobileField;
        
        private string pf_peplymanField;
        
        /// <remarks/>
        public int pf_id {
            get {
                return this.pf_idField;
            }
            set {
                this.pf_idField = value;
            }
        }
        
        /// <remarks/>
        public string pf_uid {
            get {
                return this.pf_uidField;
            }
            set {
                this.pf_uidField = value;
            }
        }
        
        /// <remarks/>
        public string pf_uname {
            get {
                return this.pf_unameField;
            }
            set {
                this.pf_unameField = value;
            }
        }
        
        /// <remarks/>
        public string pf_question {
            get {
                return this.pf_questionField;
            }
            set {
                this.pf_questionField = value;
            }
        }
        
        /// <remarks/>
        public string pf_answer {
            get {
                return this.pf_answerField;
            }
            set {
                this.pf_answerField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime pf_askdate {
            get {
                return this.pf_askdateField;
            }
            set {
                this.pf_askdateField = value;
            }
        }
        
        /// <remarks/>
        public string pf_askemail {
            get {
                return this.pf_askemailField;
            }
            set {
                this.pf_askemailField = value;
            }
        }
        
        /// <remarks/>
        public int pe_id {
            get {
                return this.pe_idField;
            }
            set {
                this.pe_idField = value;
            }
        }
        
        /// <remarks/>
        public string pf_askmobile {
            get {
                return this.pf_askmobileField;
            }
            set {
                this.pf_askmobileField = value;
            }
        }
        
        /// <remarks/>
        public string pf_peplyman {
            get {
                return this.pf_peplymanField;
            }
            set {
                this.pf_peplymanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SMC_PackageManual : BaseEntry {
        
        private int pm_idField;
        
        private string pm_nameField;
        
        private string pm_urlField;
        
        private System.DateTime pm_createdtimeField;
        
        private System.DateTime pm_updatetimeField;
        
        private int pe_idField;
        
        /// <remarks/>
        public int pm_id {
            get {
                return this.pm_idField;
            }
            set {
                this.pm_idField = value;
            }
        }
        
        /// <remarks/>
        public string pm_name {
            get {
                return this.pm_nameField;
            }
            set {
                this.pm_nameField = value;
            }
        }
        
        /// <remarks/>
        public string pm_url {
            get {
                return this.pm_urlField;
            }
            set {
                this.pm_urlField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime pm_createdtime {
            get {
                return this.pm_createdtimeField;
            }
            set {
                this.pm_createdtimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime pm_updatetime {
            get {
                return this.pm_updatetimeField;
            }
            set {
                this.pm_updatetimeField = value;
            }
        }
        
        /// <remarks/>
        public int pe_id {
            get {
                return this.pe_idField;
            }
            set {
                this.pe_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SMC_PackagePicture : BaseEntry {
        
        private int pp_idField;
        
        private int pe_idField;
        
        private string pp_pathField;
        
        private System.DateTime pp_CreatedDateField;
        
        private string pp_descField;
        
        private string pp_titleField;
        
        /// <remarks/>
        public int pp_id {
            get {
                return this.pp_idField;
            }
            set {
                this.pp_idField = value;
            }
        }
        
        /// <remarks/>
        public int pe_id {
            get {
                return this.pe_idField;
            }
            set {
                this.pe_idField = value;
            }
        }
        
        /// <remarks/>
        public string pp_path {
            get {
                return this.pp_pathField;
            }
            set {
                this.pp_pathField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime pp_CreatedDate {
            get {
                return this.pp_CreatedDateField;
            }
            set {
                this.pp_CreatedDateField = value;
            }
        }
        
        /// <remarks/>
        public string pp_desc {
            get {
                return this.pp_descField;
            }
            set {
                this.pp_descField = value;
            }
        }
        
        /// <remarks/>
        public string pp_title {
            get {
                return this.pp_titleField;
            }
            set {
                this.pp_titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SMC_User : BaseEntry {
        
        private int u_IDField;
        
        private string u_UIDField;
        
        private string u_NAMEField;
        
        private string u_UNITCODEField;
        
        private string u_PASSWORDField;
        
        private System.DateTime u_CREATEDDATEField;
        
        /// <remarks/>
        public int U_ID {
            get {
                return this.u_IDField;
            }
            set {
                this.u_IDField = value;
            }
        }
        
        /// <remarks/>
        public string U_UID {
            get {
                return this.u_UIDField;
            }
            set {
                this.u_UIDField = value;
            }
        }
        
        /// <remarks/>
        public string U_NAME {
            get {
                return this.u_NAMEField;
            }
            set {
                this.u_NAMEField = value;
            }
        }
        
        /// <remarks/>
        public string U_UNITCODE {
            get {
                return this.u_UNITCODEField;
            }
            set {
                this.u_UNITCODEField = value;
            }
        }
        
        /// <remarks/>
        public string U_PASSWORD {
            get {
                return this.u_PASSWORDField;
            }
            set {
                this.u_PASSWORDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime U_CREATEDDATE {
            get {
                return this.u_CREATEDDATEField;
            }
            set {
                this.u_CREATEDDATEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SMC_UnitSyncCompletedEventHandler(object sender, SMC_UnitSyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SMC_UnitSyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SMC_UnitSyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SMC_UserSyncCompletedEventHandler(object sender, SMC_UserSyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SMC_UserSyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SMC_UserSyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PackagePictuerSyncCompletedEventHandler(object sender, PackagePictuerSyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackagePictuerSyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PackagePictuerSyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PackageManualSyncCompletedEventHandler(object sender, PackageManualSyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageManualSyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PackageManualSyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PackageFAQSyncCompletedEventHandler(object sender, PackageFAQSyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageFAQSyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PackageFAQSyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PackageExtSyncCompletedEventHandler(object sender, PackageExtSyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageExtSyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PackageExtSyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void PackageFilesSyncCompletedEventHandler(object sender, PackageFilesSyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackageFilesSyncCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PackageFilesSyncCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591