//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1022
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICommandSvc")]
public interface ICommandSvc
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandSvc/ExecCommandByThread", ReplyAction="http://tempuri.org/ICommandSvc/ExecCommandByThreadResponse")]
    void ExecCommandByThread(string CmdCode, string _params);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommandSvc/ExecCommand", ReplyAction="http://tempuri.org/ICommandSvc/ExecCommandResponse")]
    string ExecCommand(string CmdCode, string _params);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICommandSvcChannel : ICommandSvc, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CommandSvcClient : System.ServiceModel.ClientBase<ICommandSvc>, ICommandSvc
{
    
    public CommandSvcClient()
    {
    }
    
    public CommandSvcClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CommandSvcClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CommandSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CommandSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void ExecCommandByThread(string CmdCode, string _params)
    {
        base.Channel.ExecCommandByThread(CmdCode, _params);
    }
    
    public string ExecCommand(string CmdCode, string _params)
    {
        return base.Channel.ExecCommand(CmdCode, _params);
    }
}
